-- Local FAMILY and OWN-scope pgTAP proof. Only synthetic Auth users persist.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = extensions, pg_catalog, public;
SELECT plan(41);
SELECT is((SELECT count(*) FROM auth.users WHERE email IN ('foundation-family-001@example.invalid','foundation-own-001@example.invalid','foundation-own-002@example.invalid')),3::bigint,'three dedicated local Auth users exist');
SELECT set_config('schoolos_test.family_subject',(SELECT id::text FROM auth.users WHERE email='foundation-family-001@example.invalid'),true);
SELECT set_config('schoolos_test.a_subject',(SELECT id::text FROM auth.users WHERE email='foundation-own-001@example.invalid'),true);
SELECT set_config('schoolos_test.b_subject',(SELECT id::text FROM auth.users WHERE email='foundation-own-002@example.invalid'),true);
SET ROLE schoolos_schema_owner;
INSERT INTO app_private.principals(id,kind,label,system_purpose,state,created_by) VALUES('00000001-0000-4000-8000-000000000001','SYSTEM','OWN reconciliation actor','identity-reconciliation','ACTIVE','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.principals(id,kind,person_id,label,state,created_by) VALUES('00000002-0000-4000-8000-000000000002','FAMILY',NULL,'Synthetic family','ACTIVE','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.people(id,display_name,created_by) VALUES('00000003-0000-4000-8000-000000000003','Synthetic Person A','00000001-0000-4000-8000-000000000001'),('00000004-0000-4000-8000-000000000004','Synthetic Person B','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.principals(id,kind,person_id,label,state,created_by) VALUES('00000005-0000-4000-8000-000000000005','INDIVIDUAL','00000003-0000-4000-8000-000000000003','Principal A','ACTIVE','00000001-0000-4000-8000-000000000001'),('00000006-0000-4000-8000-000000000006','INDIVIDUAL','00000004-0000-4000-8000-000000000004','Principal B','ACTIVE','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.principal_auth_bindings(id,principal_id,principal_kind,auth_user_id,bound_at,tokens_valid_from,created_by) VALUES('00000007-0000-4000-8000-000000000007','00000002-0000-4000-8000-000000000002','FAMILY',current_setting('schoolos_test.family_subject')::uuid,clock_timestamp(),to_timestamp(floor(extract(epoch FROM clock_timestamp()))),'00000001-0000-4000-8000-000000000001'),('00000008-0000-4000-8000-000000000008','00000005-0000-4000-8000-000000000005','INDIVIDUAL',current_setting('schoolos_test.a_subject')::uuid,clock_timestamp(),to_timestamp(floor(extract(epoch FROM clock_timestamp()))),'00000001-0000-4000-8000-000000000001'),('00000009-0000-4000-8000-000000000009','00000006-0000-4000-8000-000000000006','INDIVIDUAL',current_setting('schoolos_test.b_subject')::uuid,clock_timestamp(),to_timestamp(floor(extract(epoch FROM clock_timestamp()))),'00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.roles(id,code,label,family_only,state,created_by) VALUES('0000000a-0000-4000-8000-00000000000a','own-family','Synthetic family role',true,'ACTIVE','00000001-0000-4000-8000-000000000001'),('0000000b-0000-4000-8000-00000000000b','own-staff','Synthetic staff role',false,'ACTIVE','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.permissions(id,code,family_safe,state,created_by) VALUES('0000000c-0000-4000-8000-00000000000c','notification.own',true,'ENABLED','00000001-0000-4000-8000-000000000001'),('0000000d-0000-4000-8000-00000000000d','notification.preference.own',false,'ENABLED','00000001-0000-4000-8000-000000000001'),('0000000e-0000-4000-8000-00000000000e','principal.self',false,'ENABLED','00000001-0000-4000-8000-000000000001'),('0000000f-0000-4000-8000-00000000000f','campus.view',false,'ENABLED','00000001-0000-4000-8000-000000000001');
RESET ROLE;
SELECT is((SELECT count(*) FROM app_private.principal_binding_events WHERE binding_id IN ('00000007-0000-4000-8000-000000000007','00000008-0000-4000-8000-000000000008','00000009-0000-4000-8000-000000000009') AND event_kind='BOUND'),3::bigint,'three binding history events generated by triggers');
SELECT is((SELECT count(*) FROM app_private.audit_events WHERE event_type='identity.binding_changed' AND target_ref IN ('00000007-0000-4000-8000-000000000007','00000008-0000-4000-8000-000000000008','00000009-0000-4000-8000-000000000009')),3::bigint,'three binding audit events generated by triggers');
SELECT throws_ok($sql$INSERT INTO app_private.principal_role_assignments(principal_id,principal_kind,role_id,role_family_only,context_kind,valid_from,created_by) VALUES('00000002-0000-4000-8000-000000000002','FAMILY','0000000b-0000-4000-8000-00000000000b',false,'FAMILY',statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001')$sql$,'23514'::character(5),'new row for relation "principal_role_assignments" violates check constraint "principal_role_assignments_ck_02"','FAMILY cannot receive non-family staff role');
SELECT throws_ok($sql$INSERT INTO app_private.role_permission_grants(role_id,role_family_only,permission_id,permission_family_safe,valid_from,created_by) VALUES('0000000a-0000-4000-8000-00000000000a',true,'0000000f-0000-4000-8000-00000000000f',false,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001')$sql$,'23514'::character(5),'new row for relation "role_permission_grants" violates check constraint "role_permission_grants_ck_01"','family-only role cannot receive unsafe campus grant');
SET ROLE schoolos_schema_owner;
INSERT INTO app_private.role_permission_grants(id,role_id,role_family_only,permission_id,permission_family_safe,valid_from,created_by) VALUES('00000010-0000-4000-8000-000000000010','0000000a-0000-4000-8000-00000000000a',true,'0000000c-0000-4000-8000-00000000000c',true,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000011-0000-4000-8000-000000000011','0000000b-0000-4000-8000-00000000000b',false,'0000000c-0000-4000-8000-00000000000c',true,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000012-0000-4000-8000-000000000012','0000000b-0000-4000-8000-00000000000b',false,'0000000d-0000-4000-8000-00000000000d',false,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000013-0000-4000-8000-000000000013','0000000b-0000-4000-8000-00000000000b',false,'0000000e-0000-4000-8000-00000000000e',false,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000014-0000-4000-8000-000000000014','0000000b-0000-4000-8000-00000000000b',false,'0000000f-0000-4000-8000-00000000000f',false,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.principal_role_assignments(id,principal_id,principal_kind,role_id,role_family_only,context_kind,valid_from,created_by) VALUES('00000015-0000-4000-8000-000000000015','00000002-0000-4000-8000-000000000002','FAMILY','0000000a-0000-4000-8000-00000000000a',true,'FAMILY',statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000016-0000-4000-8000-000000000016','00000005-0000-4000-8000-000000000005','INDIVIDUAL','0000000b-0000-4000-8000-00000000000b',false,'INDIVIDUAL',statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000017-0000-4000-8000-000000000017','00000006-0000-4000-8000-000000000006','INDIVIDUAL','0000000b-0000-4000-8000-00000000000b',false,'INDIVIDUAL',statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.permission_scope_contracts(id,permission_id,scope_kind,resolver_key,enabled,created_by) VALUES('00000018-0000-4000-8000-000000000018','0000000c-0000-4000-8000-00000000000c','OWN','SELF_PRINCIPAL',true,'00000001-0000-4000-8000-000000000001'),('00000019-0000-4000-8000-000000000019','0000000d-0000-4000-8000-00000000000d','OWN','SELF_PRINCIPAL',true,'00000001-0000-4000-8000-000000000001'),('0000001a-0000-4000-8000-00000000001a','0000000e-0000-4000-8000-00000000000e','OWN','SELF_PRINCIPAL',true,'00000001-0000-4000-8000-000000000001'),('0000001b-0000-4000-8000-00000000001b','0000000f-0000-4000-8000-00000000000f','CAMPUS','DIRECT',true,'00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.school_profiles(id,code,name,timezone,currency_code,locale,created_by) VALUES('00000022-0000-4000-8000-000000000022','OWN-LOCAL','OWN synthetic school','UTC','USD','en','00000001-0000-4000-8000-000000000001');
INSERT INTO app.campuses(id,school_id,code,name,state,created_by) VALUES('00000023-0000-4000-8000-000000000023','00000022-0000-4000-8000-000000000022','A','Staff Campus A','ACTIVE','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.assignment_permission_scopes(id,assignment_id,grant_id,role_id,permission_id,scope_contract_id,scope_kind,resolver_key,campus_id,valid_from,created_by) VALUES('0000001c-0000-4000-8000-00000000001c','00000015-0000-4000-8000-000000000015','00000010-0000-4000-8000-000000000010','0000000a-0000-4000-8000-00000000000a','0000000c-0000-4000-8000-00000000000c','00000018-0000-4000-8000-000000000018','OWN','SELF_PRINCIPAL',NULL,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('0000001d-0000-4000-8000-00000000001d','00000016-0000-4000-8000-000000000016','00000011-0000-4000-8000-000000000011','0000000b-0000-4000-8000-00000000000b','0000000c-0000-4000-8000-00000000000c','00000018-0000-4000-8000-000000000018','OWN','SELF_PRINCIPAL',NULL,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('0000001e-0000-4000-8000-00000000001e','00000016-0000-4000-8000-000000000016','00000012-0000-4000-8000-000000000012','0000000b-0000-4000-8000-00000000000b','0000000d-0000-4000-8000-00000000000d','00000019-0000-4000-8000-000000000019','OWN','SELF_PRINCIPAL',NULL,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('0000001f-0000-4000-8000-00000000001f','00000016-0000-4000-8000-000000000016','00000013-0000-4000-8000-000000000013','0000000b-0000-4000-8000-00000000000b','0000000e-0000-4000-8000-00000000000e','0000001a-0000-4000-8000-00000000001a','OWN','SELF_PRINCIPAL',NULL,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001'),('00000021-0000-4000-8000-000000000021','00000016-0000-4000-8000-000000000016','00000014-0000-4000-8000-000000000014','0000000b-0000-4000-8000-00000000000b','0000000f-0000-4000-8000-00000000000f','0000001b-0000-4000-8000-00000000001b','CAMPUS','DIRECT','00000023-0000-4000-8000-000000000023',statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.operation_contracts(id,code,handler_key,request_permission_id,created_by) VALUES('00000024-0000-4000-8000-000000000024','OWN_TEST_NOTICE','LOCAL_TEST','0000000c-0000-4000-8000-00000000000c','00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.command_receipts(id,principal_id,operation_id,command_kind,idempotency_key,canonical_payload_hash,state,result_kind,completed_at,created_by) VALUES('00000025-0000-4000-8000-000000000025','00000001-0000-4000-8000-000000000001','00000024-0000-4000-8000-000000000024','OwnTestNotice','one',decode(repeat('ab',32),'hex'),'SUCCEEDED','TEST',clock_timestamp(),'00000001-0000-4000-8000-000000000001');
INSERT INTO app_private.outbox_events(id,event_type,aggregate_kind,aggregate_ref,aggregate_version,command_receipt_id,event_ordinal,correlation_id,payload,created_by) VALUES('00000026-0000-4000-8000-000000000026','local.own_test','principal','00000005-0000-4000-8000-000000000005',1,'00000025-0000-4000-8000-000000000025',1,'0000002c-0000-4000-8000-00000000002c','{}'::jsonb,'00000001-0000-4000-8000-000000000001');
INSERT INTO app.notifications(id,recipient_id,recipient_kind,event_id,category_code,context_key,summary,created_by) VALUES('00000027-0000-4000-8000-000000000027','00000002-0000-4000-8000-000000000002','FAMILY','00000026-0000-4000-8000-000000000026','FOUNDATION_TEST','LOCAL','{"message":"family"}'::jsonb,'00000001-0000-4000-8000-000000000001'),('00000028-0000-4000-8000-000000000028','00000005-0000-4000-8000-000000000005','INDIVIDUAL','00000026-0000-4000-8000-000000000026','FOUNDATION_TEST','LOCAL','{"message":"a"}'::jsonb,'00000001-0000-4000-8000-000000000001'),('00000029-0000-4000-8000-000000000029','00000006-0000-4000-8000-000000000006','INDIVIDUAL','00000026-0000-4000-8000-000000000026','FOUNDATION_TEST','LOCAL','{"message":"b"}'::jsonb,'00000001-0000-4000-8000-000000000001');
INSERT INTO app.notification_preferences(id,principal_id,category_code,channel_code,enabled,created_by) VALUES('0000002a-0000-4000-8000-00000000002a','00000005-0000-4000-8000-000000000005','FOUNDATION_TEST','IN_APP',true,'00000001-0000-4000-8000-000000000001'),('0000002b-0000-4000-8000-00000000002b','00000006-0000-4000-8000-000000000006','FOUNDATION_TEST','IN_APP',true,'00000001-0000-4000-8000-000000000001');
RESET ROLE;
SELECT set_config('schoolos_test.family_cutoff',(SELECT extract(epoch FROM tokens_valid_from)::bigint::text FROM app_private.principal_auth_bindings WHERE id='00000007-0000-4000-8000-000000000007'),true);
SELECT set_config('schoolos_test.a_cutoff',(SELECT extract(epoch FROM tokens_valid_from)::bigint::text FROM app_private.principal_auth_bindings WHERE id='00000008-0000-4000-8000-000000000008'),true);
SELECT set_config('schoolos_test.b_cutoff',(SELECT extract(epoch FROM tokens_valid_from)::bigint::text FROM app_private.principal_auth_bindings WHERE id='00000009-0000-4000-8000-000000000009'),true);
-- FAMILY has a complete family-safe OWN inbox chain. An unrelated staff campus chain exists.
SELECT set_config('request.jwt.claim.sub',current_setting('schoolos_test.family_subject'),true);
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('schoolos_test.family_subject'),'role','authenticated','iat',current_setting('schoolos_test.family_cutoff')::bigint,'is_anonymous',false)::text,true);
SET ROLE authenticated;
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000027-0000-4000-8000-000000000027'),1::bigint,'FAMILY reads its own family-safe notification');
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028'),0::bigint,'FAMILY cannot read A notification');
SELECT is((SELECT count(*) FROM app.campuses WHERE id='00000023-0000-4000-8000-000000000023'),0::bigint,'FAMILY cannot mix into staff Campus grant');
RESET ROLE;
SELECT is((SELECT count(*) FROM app_private.principal_role_assignments WHERE id='00000015-0000-4000-8000-000000000015' AND role_id='0000000a-0000-4000-8000-00000000000a'),1::bigint,'FAMILY assignment is a family-only role');
SELECT is((SELECT count(*) FROM app_private.role_permission_grants WHERE id='00000014-0000-4000-8000-000000000014' AND role_id='0000000b-0000-4000-8000-00000000000b'),1::bigint,'unrelated live staff Campus grant exists');
SELECT set_config('request.jwt.claim.sub',current_setting('schoolos_test.a_subject'),true);
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('schoolos_test.a_subject'),'role','authenticated','iat',current_setting('schoolos_test.a_cutoff')::bigint,'is_anonymous',false)::text,true);
SET ROLE authenticated;
SELECT is((SELECT count(*) FROM app.campuses WHERE id='00000023-0000-4000-8000-000000000023'),1::bigint,'A staff chain really reads Campus A');
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028'),1::bigint,'A reads own notification');
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000029-0000-4000-8000-000000000029'),0::bigint,'A cannot read B notification');
SELECT is((SELECT count(*) FROM app.notifications WHERE id IN ('00000028-0000-4000-8000-000000000028','00000029-0000-4000-8000-000000000029')),1::bigint,'two-notification query exposes only A');
SELECT is((SELECT count(*) FROM app.notification_preferences WHERE id='0000002a-0000-4000-8000-00000000002a'),1::bigint,'A reads own preference');
SELECT is((SELECT count(*) FROM app.notification_preferences WHERE id='0000002b-0000-4000-8000-00000000002b'),0::bigint,'A cannot read B preference');
SELECT is((SELECT count(*) FROM app.notification_preferences WHERE id IN ('0000002a-0000-4000-8000-00000000002a','0000002b-0000-4000-8000-00000000002b')),1::bigint,'two-preference query exposes only A');
SELECT is((SELECT count(*) FROM app.read_own_principal()),1::bigint,'A self grant returns one checked projection');
SELECT is((SELECT principal_id FROM app.read_own_principal()),'00000005-0000-4000-8000-000000000005'::uuid,'A projection identifies A, never B');
SELECT is((SELECT principal_kind || ':' || display_label FROM app.read_own_principal()),'INDIVIDUAL:Principal A','A projection has only reviewed kind and label');
RESET ROLE;
-- notification grant removed: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SET ROLE schoolos_schema_owner;
UPDATE app_private.role_permission_grants SET revoked_at=clock_timestamp() WHERE id='00000011-0000-4000-8000-000000000011';
RESET ROLE;
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028') AS n_removed \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'n_removed'::bigint,0::bigint,'revoked notification grant hides A inbox');

-- preference scope removed: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SET ROLE schoolos_schema_owner;
UPDATE app_private.assignment_permission_scopes SET revoked_at=clock_timestamp() WHERE id='0000001e-0000-4000-8000-00000000001e';
RESET ROLE;
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.notification_preferences WHERE id='0000002a-0000-4000-8000-00000000002a') AS p_removed \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'p_removed'::bigint,0::bigint,'revoked preference scope hides A preference');

-- self grant removed: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SET ROLE schoolos_schema_owner;
UPDATE app_private.role_permission_grants SET revoked_at=clock_timestamp() WHERE id='00000013-0000-4000-8000-000000000013';
RESET ROLE;
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.read_own_principal()) AS s_removed \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'s_removed'::bigint,0::bigint,'revoked principal self grant hides A projection');

SELECT set_config('request.jwt.claim.sub',current_setting('schoolos_test.b_subject'),true);
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('schoolos_test.b_subject'),'role','authenticated','iat',current_setting('schoolos_test.b_cutoff')::bigint,'is_anonymous',false)::text,true);
SET ROLE authenticated;
SELECT is((SELECT count(*) FROM app.read_own_principal()),0::bigint,'B has no self scope and receives no projection');
RESET ROLE;
SET ROLE schoolos_schema_owner;
INSERT INTO app_private.assignment_permission_scopes(id,assignment_id,grant_id,role_id,permission_id,scope_contract_id,scope_kind,resolver_key,campus_id,valid_from,created_by) VALUES('00000020-0000-4000-8000-000000000020','00000017-0000-4000-8000-000000000017','00000013-0000-4000-8000-000000000013','0000000b-0000-4000-8000-00000000000b','0000000e-0000-4000-8000-00000000000e','0000001a-0000-4000-8000-00000000001a','OWN','SELF_PRINCIPAL',NULL,statement_timestamp()-interval '1 hour','00000001-0000-4000-8000-000000000001');
RESET ROLE;
SET ROLE authenticated;
SELECT is((SELECT principal_id FROM app.read_own_principal()),'00000006-0000-4000-8000-000000000006'::uuid,'B complete own chain returns B');
SELECT is((SELECT count(*) FROM app.read_own_principal() WHERE principal_id='00000005-0000-4000-8000-000000000005'),0::bigint,'B projection excludes A');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub',current_setting('schoolos_test.a_subject'),true);
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('schoolos_test.a_subject'),'role','authenticated','iat',current_setting('schoolos_test.a_cutoff')::bigint,'is_anonymous',false)::text,true);
SET ROLE authenticated;
SELECT is((SELECT principal_id FROM app.read_own_principal()),'00000005-0000-4000-8000-000000000005'::uuid,'A remains A despite B live own authority');
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000029-0000-4000-8000-000000000029'),0::bigint,'A cannot read B inbox despite B own authority');
RESET ROLE;
-- stale A token: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SELECT set_config('request.jwt.claims',jsonb_build_object('sub',current_setting('schoolos_test.a_subject'),'role','authenticated','iat',current_setting('schoolos_test.a_cutoff')::bigint-1,'is_anonymous',false)::text,true);
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028') AS stale_n \gset
SELECT (SELECT count(*)::bigint FROM app.read_own_principal()) AS stale_s \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'stale_n'::bigint,0::bigint,'stale A token hides own notification');
SELECT is(:'stale_s'::bigint,0::bigint,'stale A token hides own projection');

SET ROLE authenticated;
SELECT is((SELECT count(*) FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028'),1::bigint,'iat at actual A cutoff restores own inbox');
SELECT is((SELECT count(*) FROM app.read_own_principal()),1::bigint,'iat at actual A cutoff restores own projection');
RESET ROLE;
-- SUSPENDED A: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SET ROLE schoolos_schema_owner;
UPDATE app_private.principals SET state='SUSPENDED' WHERE id='00000005-0000-4000-8000-000000000005';
RESET ROLE;
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028') AS suspended_n \gset
SELECT (SELECT count(*)::bigint FROM app.notification_preferences WHERE id='0000002a-0000-4000-8000-00000000002a') AS suspended_p \gset
SELECT (SELECT count(*)::bigint FROM app.read_own_principal()) AS suspended_s \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'suspended_n'::bigint,0::bigint,'SUSPENDED A cannot read own notification');
SELECT is(:'suspended_p'::bigint,0::bigint,'SUSPENDED A cannot read own preference');
SELECT is(:'suspended_s'::bigint,0::bigint,'SUSPENDED A cannot read own projection');

-- RETIRED A: savepoint restores the complete base chain after observing RLS.
SAVEPOINT case_state;
SET ROLE schoolos_schema_owner;
UPDATE app_private.principals SET state='RETIRED' WHERE id='00000005-0000-4000-8000-000000000005';
RESET ROLE;
SET ROLE authenticated;
SELECT (SELECT count(*)::bigint FROM app.notifications WHERE id='00000028-0000-4000-8000-000000000028') AS retired_n \gset
SELECT (SELECT count(*)::bigint FROM app.notification_preferences WHERE id='0000002a-0000-4000-8000-00000000002a') AS retired_p \gset
SELECT (SELECT count(*)::bigint FROM app.read_own_principal()) AS retired_s \gset
RESET ROLE;
ROLLBACK TO SAVEPOINT case_state;
SELECT is(:'retired_n'::bigint,0::bigint,'RETIRED A cannot read own notification');
SELECT is(:'retired_p'::bigint,0::bigint,'RETIRED A cannot read own preference');
SELECT is(:'retired_s'::bigint,0::bigint,'RETIRED A cannot read own projection');

SET ROLE authenticated;
SELECT is((SELECT count(*) FROM pg_class t JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname IN ('app','app_private') AND t.relkind='r' AND has_any_column_privilege(current_user,t.oid,'SELECT')),5::bigint,'authenticated retains exactly five reviewed table read surfaces');
SELECT ok(NOT has_any_column_privilege(current_user,'app_private.principals','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.principal_auth_bindings','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.roles','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.permissions','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.role_permission_grants','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.principal_role_assignments','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.permission_scope_contracts','SELECT') AND NOT has_any_column_privilege(current_user,'app_private.assignment_permission_scopes','SELECT'),'authenticated cannot directly SELECT private identity or RBAC inputs');
SELECT ok(NOT has_function_privilege(current_user,'app_private.current_principal_id()','EXECUTE') AND NOT has_function_privilege(current_user,'app_private.has_complete_grant(text,text,uuid)','EXECUTE'),'authenticated cannot directly execute internal helpers');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
