-- D1 employee-create business acceptance. Synthetic fixture rolls back.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path=extensions,pg_catalog,public;
SELECT plan(37);
SELECT is((SELECT count(*) FROM auth.users WHERE email='foundation-rbac-001@example.invalid'),1::bigint,'synthetic Auth subject exists');
\ir fixtures/command_actor.sql
SELECT is((SELECT count(*) FROM app_private.permissions),97::bigint,'registrar installs all permissions');
SELECT is((SELECT count(*) FROM app_private.permission_scope_contracts),322::bigint,'registrar installs all supported scopes');
SELECT is((SELECT count(*) FROM app_private.operation_contracts),36::bigint,'registrar installs all operations');
SELECT is((SELECT enabled FROM app_private.operation_contracts WHERE code='student.create'),false,'student creation remains disabled');
SELECT lives_ok('SET LOCAL ROLE schoolos_bootstrap_executor; SELECT app_private.d1_register_catalog_v1(); RESET ROLE','catalog registration is idempotent after fixture activation');
SELECT is((SELECT count(*) FROM app_private.operation_contracts),36::bigint,'second registration creates no duplicates');

SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee(NULL,'INVALID',CURRENT_DATE,'invalid')$sql$,'P0001'::char(5),'D1 Employee create intent invalid'::text,'invalid intent rejected');
SELECT throws_ok($sql$SELECT * FROM app_private.employees$sql$,'42501'::char(5),NULL::text,'client cannot read private employee rows');
SELECT throws_ok($sql$UPDATE app_private.employees SET current_state='ENDED'$sql$,'42501'::char(5),NULL::text,'client cannot mutate employee state directly');
SELECT throws_ok($sql$SELECT app_private.d1_register_catalog_v1()$sql$,'42501'::char(5),NULL::text,'client cannot invoke catalog registrar');
SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000001','EMP-ONE',CURRENT_DATE-10,'employee-one') \gset first_
SELECT is(:'first_row_version'::bigint,1::bigint,'create returns initial version');
SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000001','EMP-ONE',CURRENT_DATE-10,'employee-one') \gset replay_
SELECT is(:'replay_employee_id'::uuid,:'first_employee_id'::uuid,'same key replays same employee');
SELECT is(:'replay_row_version'::bigint,1::bigint,'same key replays original version');
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'employee-one')$sql$,'P0001'::char(5),'D1 idempotency key conflicts with prior intent'::text,'changed intent with same key rejected');
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000001','EMP-OTHER',CURRENT_DATE-10,'duplicate-person')$sql$,'P0001'::char(5),'D1 Person already has an Employee'::text,'different key cannot duplicate person');
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-ONE',CURRENT_DATE-10,'duplicate-code')$sql$,'P0001'::char(5),'D1 Employee code already exists'::text,'employee code remains unique');
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-FUTURE',CURRENT_DATE+1,'future')$sql$,'P0001'::char(5),'D1 Employee joining date cannot be in the future'::text,'future joining date denied');
RESET ROLE;
SELECT is((SELECT count(*) FROM app_private.employees),1::bigint,'failed and replayed commands create no extra employees');
SELECT is((SELECT count(*) FROM app_private.employment_periods),1::bigint,'one initial employment interval');
SELECT is((SELECT state FROM app_private.employment_periods),'ACTIVE'::text,'initial interval active');
SELECT is((SELECT effective_from FROM app_private.employment_periods),CURRENT_DATE-10,'joining date retained');
SELECT is((SELECT count(*) FROM app_private.command_receipts),1::bigint,'one durable receipt despite replay');
SELECT is((SELECT result_kind FROM app_private.command_receipts),'D1_EMPLOYEE'::text,'receipt has typed employee result');
SELECT is((SELECT principal_id FROM app_private.command_receipts),'55555555-5555-4555-8555-555555555555'::uuid,'receipt attributed to verified principal');
SELECT is((SELECT count(*) FROM app_private.audit_events WHERE event_type='employee.create'),1::bigint,'one business audit event');
SELECT is((SELECT count(*) FROM app_private.outbox_events WHERE event_type='employee.created'),1::bigint,'one outbox event');
SELECT is((SELECT payload->>'employee_id' FROM app_private.outbox_events WHERE event_type='employee.created'),:'first_employee_id','event refers to created employee');

SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.principal_role_assignments SET revoked_at=clock_timestamp() WHERE id='ffffffff-ffff-4fff-8fff-ffffffffffff';
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000001','EMP-ONE',CURRENT_DATE-10,'employee-one')$sql$,'P0001'::char(5),'D1 Employee create authority denied'::text,'replay rechecks revoked assignment');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.role_permission_grants SET revoked_at=clock_timestamp() WHERE permission_id=(SELECT id FROM app_private.permissions WHERE code='employee.create');
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'revoked-grant')$sql$,'P0001'::char(5),'D1 Employee create authority denied'::text,'revoked permission grant denies fresh command');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.assignment_permission_scopes SET revoked_at=clock_timestamp() WHERE permission_id=(SELECT id FROM app_private.permissions WHERE code='employee.create');
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'revoked-scope')$sql$,'P0001'::char(5),'D1 Employee create authority denied'::text,'revoked scope denies command');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.operation_contracts SET enabled=false WHERE code='employee.create';
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000001','EMP-ONE',CURRENT_DATE-10,'employee-one')$sql$,'P0001'::char(5),'D1 operation is not enabled'::text,'disabled operation denies even receipt replay');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.people SET state='ARCHIVED' WHERE id='10000000-0000-4000-8000-000000000002';
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'archived-person')$sql$,'P0001'::char(5),'D1 Employee Person is not active'::text,'archived person cannot become employee');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SAVEPOINT denial;
SET ROLE schoolos_schema_owner;
UPDATE app_private.principals SET state='SUSPENDED' WHERE id='55555555-5555-4555-8555-555555555555';
SET ROLE authenticated;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'suspended')$sql$,'P0001'::char(5),'D1 command requires verified actor'::text,'suspended actor rejected');
RESET ROLE;
ROLLBACK TO SAVEPOINT denial;
SET ROLE anon;
SELECT throws_ok($sql$SELECT * FROM app.d1_create_employee('10000000-0000-4000-8000-000000000002','EMP-TWO',CURRENT_DATE-10,'anon')$sql$,'42501'::char(5),NULL::text,'anonymous role cannot invoke command');
RESET ROLE;
SELECT is((SELECT count(*) FROM app_private.employees),1::bigint,'denials leave no partial employee');
SELECT is((SELECT count(*) FROM app_private.command_receipts),1::bigint,'denials leave no command receipts');
-- Force deferred commit guards before rolling synthetic rows back.
SET CONSTRAINTS ALL IMMEDIATE;
SELECT * FROM finish();
ROLLBACK;
